Migrate instance page to mobx + l10 strings
LemmurOrg/lemmur pull request #316
Opened 2022-01-14 18:14 UTC by shilangyu

2022-01-14 18:16 UTC, shilangyu commented on lib/util/extensions/context.dart
> +  Jwt? defaultJwt(String instanceHost) =>
Added it since I noticed we very often do `context.read<AccountsStore>().defaultUserDataFor(instanceHost)?.jwt`. If you don't like it I'll remove it

2022-01-19 21:37 UTC, krawieck requested changes

2022-01-19 21:37 UTC, krawieck commented on lib/pages/instance/instance_about_tab.dart
> +    return SingleChildScrollView(
add pull to refresh to refresh instance data

2022-01-19 21:37 UTC, krawieck commented on lib/pages/instance/instance_more_menu.dart
> +      children: [
add to this menu adding of this instance

2022-01-20 10:49 UTC, krawieck approved these changes

2022-01-20 10:50 UTC, merged